name: Bump Testnet Resources

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
  - cron: '30 18 * * *' # 6:30pm UTC / ~10:30am US PT

env:
  SOROBAN_RPC_URL: https://soroban-testnet.stellar.org
  SOROBAN_NETWORK_PASSPHRASE: Test SDF Network ; September 2015

jobs:
  bump-factory-wasm:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sL https://github.com/stellar/soroban-tools/releases/download/v20.0.0-rc.4.1/soroban-cli-20.0.0-rc.4.1-x86_64-unknown-linux-gnu.tar.gz | tar xz -C /usr/local/bin/
      - run: soroban config identity fund
      - run: soroban config identity address
      - run: >
          soroban contract bump
          --wasm-hash 4c8fa1392a052d344401ad8da9a99a66c57cbfd3871f2a2de98daa325f45512e
          --ledgers-to-expire 100000
          --durability persistent
  bump-factory-instance:
    needs: bump-factory-wasm
    runs-on: ubuntu-latest
    steps:
      - run: curl -sL https://github.com/stellar/soroban-tools/releases/download/v20.0.0-rc.4.1/soroban-cli-20.0.0-rc.4.1-x86_64-unknown-linux-gnu.tar.gz | tar xz -C /usr/local/bin/
      - run: soroban config identity fund
      - run: soroban config identity address
      - run: >
          soroban contract bump
          --id CDE23WMP24G2NL3FR5FVNHKXM2TFCENVPE5WYHASJUQZFKA3GRRANMOZ
          --ledgers-to-expire 100000
          --durability persistent
  bump-account-wasm:
    needs: bump-factory-instance
    runs-on: ubuntu-latest
    steps:
      - run: curl -sL https://github.com/stellar/soroban-tools/releases/download/v20.0.0-rc.4.1/soroban-cli-20.0.0-rc.4.1-x86_64-unknown-linux-gnu.tar.gz | tar xz -C /usr/local/bin/
      - run: soroban config identity fund
      - run: soroban config identity address
      - run: >
          soroban contract bump
          --wasm-hash a40cbcffa428add4f2ada31d904c5c03a4921e84b652b2351106f424e4aaf786
          --ledgers-to-expire 100000
          --durability persistent
